title: "[WIP]Next.jsとFirebaseによる実用Webアプリ開発"
summary: "この本は執筆途中ですが著者のリソース問題で更新を断念しました。このままお蔵入りさせるのも忍びないので途中までですが公開することにしました。ご留意の上適宜参照してください。また、Tailwind CSSなど古いバージョンに基づいているのでその点もご留意の上ご参照ください。"
topics:
  - "firebase"
  - "nextjs"
  - "tailwindcss"
  - "algolia"
published: true
price: 0
toc_depth: 2
chapters:
  - "18f9f7"
  - "d823d3"
  - "477877"
  - "24838e"
  - "0ad5df"
  - "285689"
  - "90a2a8"
  - "6f3c96"
  - "b79c9c"
  - "c959d7"
  - "610ddf"
  - "807f3b"
  - "13c6bf"
  - "87ab2f"
  - "01bf78"
  - "d432a6"
  - "43eba7"
  - "9e6ea3"
  - "0a5345"
  - "932352"
  - "858755"
  - "bb4f33"
  - "33425b"
  - "e8b1fc"
  - "7ea43c"
  - "c82a3f"
  - "80e15d"
  - "cf15d8"
  - "7816e7"
  - "9fe6c2"